'use client';

export default function PrivacyPolicy() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12 text-gray-800">
      <h1 className="text-3xl font-bold mb-8 text-center text-[#212121]">PRIVACY POLICY</h1>
      
      <div className="space-y-8">
        <section>
          <h2 className="text-2xl font-semibold mb-4 text-blue-600">1. Introduction</h2>
          <p className="mb-4">
            Welcome to Thinkagain Educational Services LLP.
          </p>
          <p className="mb-4">
            Thinkagain Educational Services LLP ("us", "we", or "our") operates www.thinkagainlab.com (hereinafter referred to as "Service").
          </p>
          <p className="mb-4">
            Our Privacy Policy governs your visit to www.thinkagainlab.com, and explains how we collect, safeguard and disclose information that results from your use of our Service.
          </p>
          <p className="mb-4">
            We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
          </p>
          <p className="mb-4">
            Our Terms and Conditions ("Terms") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("agreement").
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-green-600">2. Definitions</h2>
          <ul className="list-none space-y-2">
            <li><strong>SERVICE</strong> means the www.thinkagainlab.com website operated by Thinkagain Educational Services LLP.</li>
            <li><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
            <li><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>COOKIES</strong> are small files stored on your device (computer or mobile device).</li>
            <li><strong>DATA CONTROLLER</strong> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</li>
            <li><strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</li>
            <li><strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.</li>
            <li><strong>THE USER</strong> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-blue-600">3. Information Collection and Use</h2>
          <p className="mb-4">
            We collect several different types of information for various purposes to provide and improve our Service to you.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-green-600">4. Types of Data Collected</h2>
          
          <h3 className="text-xl font-medium mb-2 text-[#212121]">Personal Data</h3>
          <p className="mb-4">
            While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc pl-8 mb-4 space-y-1">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, Country, State, Province, ZIP/Postal code, City</li>
            <li>Cookies and Usage Data</li>
          </ul>
          <p className="mb-6">
            We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
          </p>

          <h3 className="text-xl font-medium mb-2 text-[#212121]">Usage Data</h3>
          <p className="mb-4">
            We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device ("Usage Data").
          </p>
          <p className="mb-4">
            This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p className="mb-6">
            When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.
          </p>

          <h3 className="text-xl font-medium mb-2 text-[#212121]">Location Data</h3>
          <p className="mb-4">
            We may use and store information about your location if you give us permission to do so ("Location Data"). We use this data to provide features of our Service, to improve and customize our Service.
          </p>
          <p className="mb-6">
            You can enable or disable location services when you use our Service at any time by way of your device settings.
          </p>

          <h3 className="text-xl font-medium mb-2 text-[#212121]">Tracking Cookies Data</h3>
          <p className="mb-4">
            We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
          </p>
          <p className="mb-4">
            Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
          </p>
          <p className="mb-4">
            You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
          </p>
          <p className="mb-4">
            Examples of Cookies we use:
          </p>
          <ul className="list-disc pl-8 mb-4 space-y-1">
            <li>Session Cookies: We use Session Cookies to operate our Service.</li>
            <li>Preference Cookies: We use Preference Cookies to remember your preferences and various settings.</li>
            <li>Security Cookies: We use Security Cookies for security purposes.</li>
            <li>Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
          </ul>

          <h3 className="text-xl font-medium mb-2 text-[#212121]">Other Data</h3>
          <p className="mb-4">
            While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, non-disclosure agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-blue-600">5. Use of Data</h2>
          <p className="mb-4">
            Thinkagain Educational Services LLP uses the collected data for various purposes:
          </p>
          <ul className="list-disc pl-8 mb-4 space-y-1">
            <li>to provide and maintain our Service;</li>
            <li>to notify you about changes to our Service;</li>
            <li>to allow you to participate in interactive features of our Service when you choose to do so;</li>
            <li>to provide customer support;</li>
            <li>to gather analysis or valuable information so that we can improve our Service;</li>
            <li>to monitor the usage of our Service;</li>
            <li>to detect, prevent and address technical issues;</li>
            <li>to fulfil any other purpose for which you provide it;</li>
            <li>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
            <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
            <li>to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
            <li>in any other way we may describe when you provide the information;</li>
            <li>for any other purpose with your consent.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-green-600">6. Retention of Data</h2>
          <p className="mb-4">
            We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
          </p>
          <p className="mb-4">
            We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-blue-600">7. Transfer of Data</h2>
          <p className="mb-4">
            Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
          </p>
          <p className="mb-4">
            If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.
          </p>
          <p className="mb-4">
            Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
          </p>
          <p className="mb-4">
            Thinkagain Educational Services LLP will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-green-600">8. Disclosure of Data</h2>
          <p className="mb-4">
            We may disclose personal information that we collect, or you provide:
          </p>
          <h3 className="text-xl font-medium mb-2 text-[#212121]">0.1. Disclosure for Law Enforcement.</h3>
          <p className="mb-4">
            Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
          </p>
          <h3 className="text-xl font-medium mb-2 text-[#212121]">0.2. Business Transaction.</h3>
          <p className="mb-4">
            If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
          </p>
          <h3 className="text-xl font-medium mb-2 text-[#212121]">0.3. Other cases. We may disclose your information also:</h3>
          <ul className="list-disc pl-8 mb-4 space-y-1">
            <li>to our subsidiaries and affiliates;</li>
            <li>to contractors, service providers, and other third parties we use to support our business;</li>
            <li>to fulfill the purpose for which you provide it;</li>
            <li>for the purpose of including your company's logo on our website;</li>
            <li>for any other purpose disclosed by us when you provide the information;</li>
            <li>with your consent in any other cases;</li>
            <li>if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-blue-600">9. Security of Data</h2>
          <p className="mb-4">
            The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-green-600">10. Service Providers</h2>
          <p className="mb-4">
            We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
          </p>
          <p className="mb-4">
            These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-blue-600">11. Analytics</h2>
          <p className="mb-4">
            We may use third-party Service Providers to monitor and analyze the use of our Service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-green-600">12. CI/CD tools</h2>
          <p className="mb-4">
            We may use third-party Service Providers to automate the development process of our Service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-blue-600">13. Behavioral Remarketing</h2>
          <p className="mb-4">
            We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-green-600">14. Payments</h2>
          <p className="mb-4">
            We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).
          </p>
          <p className="mb-4">
            We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-blue-600">15. Links to Other Sites</h2>
          <p className="mb-4">
            Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
          </p>
          <p className="mb-4">
            We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          </p>
          <p className="mb-4">
            For example, the outlined Privacy Policy has been created using PolicyMaker.io, a free web application for generating high-quality legal documents. PolicyMaker's online privacy policy generator is an easy-to-use free tool for creating an excellent privacy policy template for a website, blog, online store or app.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-green-600">16. Children's Privacy</h2>
          <p className="mb-4">
            Our Services are not intended for use by children under the age of 18 ("Child" or "Children").
          </p>
          <p className="mb-4">
            We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-blue-600">17. Changes to This Privacy Policy</h2>
          <p className="mb-4">
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className="mb-4">
            We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update "effective date" at the top of this Privacy Policy.
          </p>
          <p className="mb-4">
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-green-600">18. Contact Us</h2>
          <p className="mb-4">
            If you have any questions about this Privacy Policy, please contact us by email: hello@thinkagainlab.com.
          </p>
        </section>
      </div>
    </div>
  );
}